FROM terrarum/alpinerubynode
MAINTAINER terrarum@gmail.com

RUN gem install --no-document jekyll -v 3.1.2
RUN gem install --no-document bundler -v 1.11.2
RUN gem install --no-document io-console -v 0.4.5
