# Microcontainers: http://www.iron.io/microcontainers-tiny-portable-containers/
# From: https://github.com/iron-io/dockers/tree/master/base
FROM terrarum/alpinerubynode

RUN gem install --no-document jekyll -v 3.1.2
RUN gem install --no-document bundler -v 1.11.2
RUN gem install --no-document io-console -v 0.4.5
